name: Deploy Online Testing Backend

on:
  push:
    branches:
      - stone04
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Rename csproj (case fix)
        shell: bash
        run: |
          # Nếu file B đã tồn tại thì bỏ qua
          if [ -f "Backend_online_testing.csproj" ]; then
            echo "Already renamed."
          else
            # Đổi tên file csproj
            mv backend_online_testing.csproj Backend_online_testing.csproj
            # Sửa tham chiếu trong .sln (nếu có)
            if [ -f "backend_online_testing.sln" ]; then
              sed -i 's/backend_online_testing\.csproj/Backend_online_testing.csproj/g' backend_online_testing.sln
            fi
          fi
          ls -l | grep -i '.*online_testing.*\.csproj' || true

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore ./Backend_online_testing.csproj

      - name: Build project
        run: dotnet build ./Backend_online_testing.csproj --configuration Release --no-restore

      - name: Publish project
        run: dotnet publish ./Backend_online_testing.csproj -c Release -o ./publish

      - name: Copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_SERVER }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          source: "./publish/*"
          target: "/var/www/online-testing-backend"

      - name: Restart backend service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_SERVER }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            echo "===== RESTART BACKEND SERVICE ====="
            sudo systemctl daemon-reload
            sudo systemctl stop online-testing.service || true
            sudo systemctl start online-testing.service
            sudo systemctl status online-testing.service --no-pager
            echo "✅ Deployment completed!"
