name: SAST

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  sast:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install semgrep

      - name: Run semgrep
        run: semgrep --config "p/csharp" --json -o semgrep-results.json . || true

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: csharp

      - name: Build project
        run: |
          dotnet build ./backend_online_testing.csproj --configuration Release

      - name: Perform CodeQL analysis
        uses: github/codeql-action/analyze@v3

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: |
            semgrep-results.json
