name: SAST

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  sast:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install semgrep

      - name: Run semgrep
        run: semgrep --config "p/csharp" --json -o semgrep-results.json . || true

      - name: Init CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: csharp

      - name: Build (capture for CodeQL DB)
        run: |
          # Use the same build command your project uses
          dotnet restore
          dotnet build

      - name: Create CodeQL database (capture)
        run: |
          codeql database create codeql-db --language=csharp --command "dotnet build"

      - name: Analyze DB -> SARIF
        run: |
          codeql database analyze codeql-db --format=sarif-latest --output=codeql-results.sarif

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: |
            semgrep-results.json
            codeql-results.sarif
