name: SCA scan

on:
  push:
    branches: [ main ]
  workflow_dispatch: 

jobs:
  dep-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore ./backend_online_testing.csproj

      - name: Scan dependencies
        uses: snyk/actions/dotnet@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --json-file-output=snyk-results.json

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dep-scan-reports
          path: |
            snyk-results.json
